### ISSUE TITLE
Remove secrets and load them using environment variables

### ISSUE THREAD

**Issue by dilip640** [Attendance-System-G14/SATS-Backend#4]

**Comment by kadarsh835** [comment]
### configure .env for Django
### update requirements.txt

**Comment by dilip640** [comment]
Loading environment variable in ```settings.py``` is sufficient because ```managy.py``` and ```wsgi.py``` itself load the settings first. Please remove from other files. Also do not give any path in ```load_dotenv()```, the ```.env``` file is supposed to be in root directory.

**Comment by kadarsh835** [comment]
As suggested on [Python Package Index](https://pypi.org/project/python-dotenv/), the lines of code were to be added in ```manage.py``` and ```wsgi.py```, but on further digging, I learnt that adding it in ```settings.py``` was enough. The correction has been made.
